"""Shared FBDI load orchestration used by both servers."""

from __future__ import annotations

from typing import Any

from .catalog import get_object
from .oracle_client import OracleERPClient


def run_load(
    *,
    base_url: str,
    username: str,
    password: str,
    object_key: str,
    mode: str,
    interface_id: str,
    run_import: str,
    wait_for_load: str,
    wait_seconds: str,
    import_parameters: str,
    filename: str,
    content: bytes,
) -> dict[str, Any]:
    spec = get_object(object_key)
    if not filename.lower().endswith(".zip"):
        raise ValueError(
            "Upload the ZIP generated by the FBDI XLSM (Generate CSV File), not the spreadsheet itself."
        )
    if not content:
        raise ValueError("Uploaded file is empty")

    iface = (interface_id or spec.get("interface_id") or "").strip()
    param_list = (import_parameters or "").strip() or "#NULL"
    client = OracleERPClient(base_url.strip(), username.strip(), password)
    result: dict[str, Any] = {
        "object": spec["key"],
        "label": spec["label"],
        "mode": mode,
        "file_name": filename,
        "ucm_account": spec["ucm_account_ui"],
        "interface_tables": spec["interface_tables"],
        "steps": [],
        "verify_sql": spec["verify_sql"],
    }

    def timeout() -> int:
        try:
            return max(30, int(wait_seconds or "300"))
        except ValueError:
            return 300

    if mode == "one_shot":
        if not iface:
            raise ValueError("Interface ID is required for one-shot importBulkData.")
        job_options = f"ExtractFileType=ALL,InterfaceDetails={iface},ImportOption=Y,PurgeOption=N"
        raw = client.import_bulk_data(
            file_bytes=content,
            file_name=filename,
            document_account=spec["ucm_account"],
            job_name=spec["import_job"]["job_name"],
            parameter_list=param_list,
            job_options=job_options,
        )
        req = str(raw.get("ReqstId") or raw.get("LoadRequestId") or "")
        result["steps"].append(
            {
                "name": "importBulkData",
                "description": "Upload ZIP to UCM + Load Interface File + Import job",
                "request_id": req,
                "document_id": raw.get("DocumentId"),
                "oracle": raw,
            }
        )
        result["load_request_id"] = req
        if wait_for_load.upper() == "Y" and req:
            waited = client.wait_for_job(req, timeout_seconds=timeout())
            result["steps"].append(
                {
                    "name": "WaitImportBulkData",
                    "request_id": req,
                    "status": waited.get("_normalizedStatus"),
                    "timed_out": bool(waited.get("_timedOut")),
                    "oracle": waited,
                }
            )
        return result

    upload = client.upload_file_to_ucm(
        file_bytes=content,
        file_name=filename,
        document_account=spec["ucm_account"],
    )
    document_id = str(upload.get("DocumentId") or "")
    result["steps"].append(
        {
            "name": "uploadFileToUCM",
            "description": f"File parked in UCM account {spec['ucm_account_ui']}",
            "document_id": document_id,
            "oracle": upload,
        }
    )
    if not document_id or document_id == "None":
        raise ValueError("UCM upload succeeded but DocumentId is missing.")
    if not iface:
        raise ValueError("Interface ID is required. Use Lookup Interface ID first.")

    load_params = f"{iface},{document_id},N,N"
    load = client.submit_ess_job(
        spec["load_job"]["package"],
        spec["load_job"]["definition"],
        load_params,
    )
    load_req = str(load.get("ReqstId") or "")
    result["steps"].append(
        {
            "name": "LoadInterfaceFileForImport",
            "description": "ESS InterfaceLoaderController — CSV rows into interface tables",
            "request_id": load_req,
            "ess_parameters": load_params,
            "oracle": load,
        }
    )
    result["load_request_id"] = load_req
    result["document_id"] = document_id

    load_status = ""
    if wait_for_load.upper() == "Y" and load_req:
        waited = client.wait_for_job(load_req, timeout_seconds=timeout())
        load_status = waited.get("_normalizedStatus") or ""
        result["steps"].append(
            {
                "name": "WaitLoadInterface",
                "request_id": load_req,
                "status": load_status,
                "timed_out": bool(waited.get("_timedOut")),
                "oracle": waited,
            }
        )
        try:
            logs = client.get_ess_job_details(load_req, file_type="log")
            result["steps"].append({"name": "LoadJobLog", "request_id": load_req, "oracle": logs})
        except Exception as log_exc:
            result["steps"].append({"name": "LoadJobLog", "error": str(log_exc)})

    should_import = run_import.upper() == "Y"
    if should_import and wait_for_load.upper() == "Y" and load_status not in {"SUCCEEDED", "WARNING", ""}:
        result["import_skipped"] = True
        result["import_skip_reason"] = (
            f"Import not submitted because interface load ended with {load_status}."
        )
        return result

    if should_import:
        imp = client.submit_ess_job(
            spec["import_job"]["package"],
            spec["import_job"]["definition"],
            param_list,
        )
        import_req = str(imp.get("ReqstId") or "")
        result["steps"].append(
            {
                "name": spec["import_job"]["display"],
                "description": "Module import — interface rows into application tables",
                "request_id": import_req,
                "ess_parameters": param_list,
                "oracle": imp,
            }
        )
        result["import_request_id"] = import_req
        if import_req in {"", "-1", "None"}:
            result["import_skipped"] = True
            result["import_skip_reason"] = (
                "Fusion returned ReqstId -1. The import job name or ParameterList is invalid, "
                "or the user cannot submit Import Suppliers. Run Import Suppliers from "
                "Scheduled Processes instead."
            )
            return result
        if import_req and wait_for_load.upper() == "Y":
            waited_imp = client.wait_for_job(import_req, timeout_seconds=timeout())
            result["steps"].append(
                {
                    "name": "WaitImport",
                    "request_id": import_req,
                    "status": waited_imp.get("_normalizedStatus"),
                    "timed_out": bool(waited_imp.get("_timedOut")),
                    "oracle": waited_imp,
                }
            )
    return result
