"""Fusion FBDI Load Console — FastAPI backend."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from .catalog import get_object, list_objects
from .oracle_client import OracleERPClient

load_dotenv()

STATIC_DIR = Path(__file__).resolve().parent.parent / "static"

app = FastAPI(
    title="Fusion FBDI Load Console",
    description="Upload an FBDI ZIP to UCM, load interface tables, then import to base tables.",
    version="1.0.0",
)

if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


class ConnectionBody(BaseModel):
    base_url: str = Field(..., min_length=8)
    username: str = Field(..., min_length=1)
    password: str = Field(..., min_length=1)


class StatusBody(ConnectionBody):
    request_id: str = Field(..., min_length=1)


class LookupBody(ConnectionBody):
    object_key: str


def _client(base_url: str, username: str, password: str) -> OracleERPClient:
    return OracleERPClient(base_url=base_url.strip(), username=username.strip(), password=password)


def _join_params(values: list[str]) -> str:
    cleaned = []
    for value in values:
        text = (value or "").strip()
        cleaned.append(text if text else "#NULL")
    return ",".join(cleaned)


@app.get("/")
def index() -> FileResponse:
    index_file = STATIC_DIR / "index.html"
    if not index_file.exists():
        raise HTTPException(status_code=500, detail="UI is missing")
    return FileResponse(index_file)


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/defaults")
def defaults() -> dict[str, str]:
    return {
        "base_url": os.getenv("ORACLE_BASE_URL", ""),
        "username": os.getenv("ORACLE_USERNAME", ""),
        "has_password": bool(os.getenv("ORACLE_PASSWORD")),
        "data_access_set": os.getenv("DEFAULT_DATA_ACCESS_SET", ""),
        "ledger_id": os.getenv("DEFAULT_LEDGER_ID", ""),
        "business_unit": os.getenv("DEFAULT_BUSINESS_UNIT", ""),
        "journal_source": os.getenv("DEFAULT_JOURNAL_SOURCE", "Spreadsheet"),
        "ap_source": os.getenv("DEFAULT_AP_SOURCE", "Spreadsheet"),
    }


@app.get("/api/objects")
def objects() -> list[dict[str, Any]]:
    return list_objects()


@app.post("/api/ping")
def ping(body: ConnectionBody) -> dict[str, Any]:
    try:
        return _client(body.base_url, body.username, body.password).ping()
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/lookup-interface")
def lookup_interface(body: LookupBody) -> dict[str, Any]:
    try:
        spec = get_object(body.object_key)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    try:
        raw = _client(body.base_url, body.username, body.password).inbound_process_details(
            spec["import_job"]["job_name"]
        )
        return {"object": spec["key"], "job_name": spec["import_job"]["job_name"], "oracle": raw}
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/status")
def job_status(body: StatusBody) -> dict[str, Any]:
    try:
        return _client(body.base_url, body.username, body.password).get_ess_job_status(
            body.request_id
        )
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/job-details")
def job_details(body: StatusBody) -> dict[str, Any]:
    try:
        return _client(body.base_url, body.username, body.password).get_ess_job_details(
            body.request_id, file_type="log"
        )
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/load")
async def load(
    base_url: str = Form(...),
    username: str = Form(...),
    password: str = Form(...),
    object_key: str = Form(...),
    mode: str = Form("two_step"),
    interface_id: str = Form(""),
    run_import: str = Form("Y"),
    wait_for_load: str = Form("Y"),
    wait_seconds: str = Form("300"),
    import_parameters: str = Form(""),
    file: UploadFile = File(...),
) -> dict[str, Any]:
    try:
        spec = get_object(object_key)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    filename = file.filename or "fbdi.zip"
    if not filename.lower().endswith(".zip"):
        raise HTTPException(
            status_code=400,
            detail="Upload the ZIP generated by the FBDI XLSM (Generate CSV File), not the spreadsheet itself.",
        )

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="Uploaded file is empty")

    iface = (interface_id or spec.get("interface_id") or "").strip()
    param_list = import_parameters.strip() or "#NULL"
    client = _client(base_url, username, password)
    result: dict[str, Any] = {
        "object": spec["key"],
        "label": spec["label"],
        "mode": mode,
        "file_name": filename,
        "ucm_account": spec["ucm_account_ui"],
        "interface_tables": spec["interface_tables"],
        "steps": [],
    }

    try:
        if mode == "one_shot":
            if not iface:
                raise HTTPException(
                    status_code=400,
                    detail="Interface ID is required for one-shot importBulkData (JobOptions.InterfaceDetails).",
                )
            job_options = f"ExtractFileType=ALL,InterfaceDetails={iface},ImportOption=Y,PurgeOption=N"
            raw = client.import_bulk_data(
                file_bytes=content,
                file_name=filename,
                document_account=spec["ucm_account"],
                job_name=spec["import_job"]["job_name"],
                parameter_list=param_list,
                job_options=job_options,
            )
            result["steps"].append(
                {
                    "name": "importBulkData",
                    "description": "Upload ZIP to UCM + Load Interface File + Import job",
                    "request_id": raw.get("ReqstId") or raw.get("LoadRequestId"),
                    "document_id": raw.get("DocumentId"),
                    "oracle": raw,
                }
            )
            result["load_request_id"] = raw.get("ReqstId") or raw.get("LoadRequestId")
            result["verify_sql"] = spec["verify_sql"]
            req = str(result["load_request_id"] or "")
            if wait_for_load.upper() == "Y" and req:
                try:
                    timeout = max(30, int(wait_seconds or "300"))
                except ValueError:
                    timeout = 300
                waited = client.wait_for_job(req, timeout_seconds=timeout)
                result["steps"].append(
                    {
                        "name": "WaitImportBulkData",
                        "description": "Polled importBulkData ESS request until terminal status",
                        "request_id": req,
                        "status": waited.get("_normalizedStatus"),
                        "timed_out": bool(waited.get("_timedOut")),
                        "oracle": waited,
                    }
                )
            return result

        # Two-step (recommended): upload → Load Interface File → optional Import
        upload = client.upload_file_to_ucm(
            file_bytes=content,
            file_name=filename,
            document_account=spec["ucm_account"],
        )
        document_id = str(upload.get("DocumentId") or "")
        result["steps"].append(
            {
                "name": "uploadFileToUCM",
                "description": f"File parked in UCM account {spec['ucm_account_ui']}",
                "document_id": document_id,
                "oracle": upload,
            }
        )
        if not document_id or document_id == "None":
            raise HTTPException(
                status_code=400,
                detail="UCM upload succeeded but DocumentId is missing. Check the integration user and UCM account.",
            )

        if not iface:
            raise HTTPException(
                status_code=400,
                detail="Interface ID is required to submit Load Interface File for Import. Use Lookup Interface ID.",
            )

        # InterfaceLoaderController params: InterfaceId, UCM DocumentId, Purge, Report
        load_params = f"{iface},{document_id},N,N"
        load = client.submit_ess_job(
            spec["load_job"]["package"],
            spec["load_job"]["definition"],
            load_params,
        )
        load_req = str(load.get("ReqstId") or "")
        result["steps"].append(
            {
                "name": "LoadInterfaceFileForImport",
                "description": "ESS InterfaceLoaderController — CSV rows into interface tables",
                "request_id": load_req,
                "ess_parameters": load_params,
                "oracle": load,
            }
        )
        result["load_request_id"] = load_req
        result["document_id"] = document_id
        result["verify_sql"] = spec["verify_sql"]

        load_status = ""
        if wait_for_load.upper() == "Y" and load_req:
            try:
                timeout = max(30, int(wait_seconds or "300"))
            except ValueError:
                timeout = 300
            waited = client.wait_for_job(load_req, timeout_seconds=timeout)
            load_status = waited.get("_normalizedStatus") or ""
            result["steps"].append(
                {
                    "name": "WaitLoadInterface",
                    "description": "Polled Load Interface File for Import until terminal status",
                    "request_id": load_req,
                    "status": load_status,
                    "timed_out": bool(waited.get("_timedOut")),
                    "oracle": waited,
                }
            )
            try:
                logs = client.get_ess_job_details(load_req, file_type="log")
                result["steps"].append(
                    {
                        "name": "LoadJobLog",
                        "description": "ESS log for Load Interface File for Import",
                        "request_id": load_req,
                        "oracle": logs,
                    }
                )
            except Exception as log_exc:
                result["steps"].append(
                    {
                        "name": "LoadJobLog",
                        "description": "Could not download ESS log",
                        "error": str(log_exc),
                    }
                )

        should_import = run_import.upper() == "Y"
        if should_import and wait_for_load.upper() == "Y" and load_status not in {"SUCCEEDED", "WARNING"}:
            result["import_skipped"] = True
            result["import_skip_reason"] = (
                f"Import not submitted because interface load ended with {load_status or 'unknown status'}."
            )
            return result

        if should_import:
            imp = client.submit_ess_job(
                spec["import_job"]["package"],
                spec["import_job"]["definition"],
                param_list,
            )
            import_req = str(imp.get("ReqstId") or "")
            result["steps"].append(
                {
                    "name": spec["import_job"]["display"],
                    "description": "Module import — interface rows into application tables",
                    "request_id": import_req,
                    "ess_parameters": param_list,
                    "oracle": imp,
                }
            )
            result["import_request_id"] = import_req
            if import_req and wait_for_load.upper() == "Y":
                try:
                    timeout = max(30, int(wait_seconds or "300"))
                except ValueError:
                    timeout = 300
                waited_imp = client.wait_for_job(import_req, timeout_seconds=timeout)
                result["steps"].append(
                    {
                        "name": "WaitImport",
                        "description": f"Polled {spec['import_job']['display']} until terminal status",
                        "request_id": import_req,
                        "status": waited_imp.get("_normalizedStatus"),
                        "timed_out": bool(waited_imp.get("_timedOut")),
                        "oracle": waited_imp,
                    }
                )

        return result
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
